Исправляет опечатки в разделах принципа открытости-закрытости
open-tech-authors/solid pull request #177
Opened 2022-01-16 17:49 UTC by corocoto

Исправлены опечатки в разделах принципа **открытости-закрытости**. А именно:
* Текст первого ответа на вопрос "Чем полезен механизм подписки шаблона «Наблюдатель»?"

![image](https://user-images.githubusercontent.com/37180024/149671488-7774f27d-2755-48b6-a173-65fcd483932b.png)

* Пояснительный текст для модулей, которые закрыты для изменения:
![image](https://user-images.githubusercontent.com/37180024/149671531-781da6ac-286d-428f-bf73-e4163b9c4084.png)

2022-01-16 18:44 UTC, bespoyasov requested changes
Привет! Спасибо за внимательность! 👀 

У меня есть предложение по формулировке, кажется, так будет лучше :–)

2022-01-16 18:44 UTC, bespoyasov commented on components/Quiz/quizzes/ocp-patterns-7/index.tsx
> +        'Позволяет создать объект, который уведомляет других о неком событии без необходимости связывать их напрямую'
Не уверен, что здесь подойдёт эта форма винительного падежа. «Других» подходит для одушевлённых существительных, но объекты — неодушевлённое, поэтому «уведомляет другие». 

Но мы можем исправить эту двусмыленность, добавив пояснение:

```suggestion
        'Позволяет создать объект, который уведомляет другие объекты о неком событии без необходимости связывать их напрямую'
```

2022-01-16 19:55 UTC, corocoto commented on components/Quiz/quizzes/ocp-patterns-7/index.tsx
> +        'Позволяет создать объект, который уведомляет других о неком событии без необходимости связывать их напрямую'
@bespoyasov, да, мне нравится предложенный тобой вариант. Давай оставим именно его

2022-01-17 07:54 UTC, bespoyasov approved these changes
Отлично! 
Большое спасибо :–)

2022-01-17 07:54 UTC, merged